language: cpp
compiler:
  - gcc
os: linux
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev
before_script:
 - ./build.sh
script: "./build/ConceptualMonadsTest"
branches:
  only:
    - master
